using System.Collections.Immutable;
using Glox.Registry;
using Spectre.Console;

namespace Glox.Cpp;

internal static class CppWriter
{
    private static void WritePage(DirectoryInfo folder, string page, IEnumerable<string> lines)
    {
        var path = Path.Combine(folder.FullName, page);
        File.WriteAllLines(path, lines);
    }

    internal static void Write(DirectoryInfo folder, Registry.Registry registry, NamedApi api, Version version, ProfileName? profile, ImmutableHashSet<string> ignoreEnumPrefixes)
    {
        AnsiConsole.WriteLine("Generating code...");
        var features = registry.Features.Where(x => x.Api == api && x.Number <= version).OrderBy(x => x.Number);
        Selection sel = new();
        foreach (var feat in features)
        {
            foreach (var add in feat.Require)
            {
                if (Include(profile, add))
                {
                    sel.Add(add);
                }
            }

            foreach (var add in feat.Remove)
            {
                if (Include(profile, add))
                {
                    sel.Remove(add);
                }
            }
        }

        // todo(Gustav): collect types
        var typeFinder = new TypeFinder();
        VisitParam(sel, typeFinder);
        VisitPrototype(sel, typeFinder);
        var types = typeFinder.Types.OrderBy(t => t.DeclarationIndex).ToImmutableArray();

        // todo(Gustav): group enums values into groups
        var groupFinder = new GroupFinder();
        VisitParam(sel, groupFinder);
        VisitPrototype(sel, groupFinder);
        foreach (var m in groupFinder.Groups.Select(x => new { Group = x.Key, Types = x.Value }).Where(x => x.Types.Count > 1))
        {
            var tooManyTypes = string.Join(", ", m.Types.Select(x => x.Name));
            AnsiConsole.MarkupLineInterpolated($"{m.Group.Name} has many types: {tooManyTypes}");
        }
        var enumGroups = groupFinder.Groups.Select(x => new { Group = x.Key, Type = x.Value.FirstOrDefault(), Values = new List<EnumValue>() }).ToImmutableArray();
        var enumGroupLookup = enumGroups.ToImmutableDictionary(x => x.Group, x => x);
        var unusedEnums = sel.EnumValues.ToHashSet();
        foreach (var enumVal in sel.EnumValues)
        {
            bool added = false;
            foreach (var enumGroup in enumVal.Groups)
            {
                if (!enumGroupLookup.TryGetValue(enumGroup, out var dstGroup)) continue;
                dstGroup.Values.Add(enumVal);
                added = true;
            }

            if (added)
            {
                unusedEnums.Remove(enumVal);
            }
        }

        // todo(Gustav): fix command prefixes
        // todo(Gustav): replace naked types with classes
        // todo(Gustav: figure out how to use kinds... replacement function/factories
        // todo(Gustav): multiple enum values?

        AnsiConsole.WriteLine("Typing code...");
        SimpleWriter code = new();
        code.Header("#pragma once");
        code.Source("#include \"glox.hh\"");
        code.Add("");
        code.Add("// Code generated by the glox-sharp generator");
        code.Add("");
        WriteTypes(code, types.Where(t => t.GotAttributeFromName));
        code.Add("");
        code.Add("namespace gl");
        code.Add("{");

        code.Header("// Types");
        WriteTypes(code, types.Where(t => t.GotAttributeFromName == false));
        code.Header("");
        code.Header("");

        code.Header("// Enum groups");
        foreach (var g in enumGroups)
        {
            if(g.Type != null)
            {
                code.Header($"enum class {g.Group.Name} : {g.Type.Name}");
            }
            else
            {
                code.Header($"enum class {g.Group.Name}");
            }
            code.Header("{");
            bool first = true;
            var prefix = g.Values.Select(e => e.Name).Where(name => ignoreEnumPrefixes.Contains(name) == false).GetCommonPrefix();
            if (prefix.Length > 0 && prefix.EndsWith("_") == false)
            {
                // prefix must end with _
                prefix += "_";
            }
            foreach (var ev in g.Values)
            {
                var s = first ? "  " : ", ";
                first = false;
                var name = RemovePrefixes(ev.Name, prefix, "GL_");
                bool startsWithNumber = name.Length > 0 && char.IsDigit(name[0]);
                if (startsWithNumber)
                {
                    name = "n" + name;
                }
                code.Header($"\t{s}{name} = {ev.Value} //< Original name was {ev.Name}");
            }
            code.Header("}");
        }
        code.Header("");
        code.Header("");

        code.Header("// Enum values not mapped to a group");
        foreach (var ev in unusedEnums)
        {
            code.Header($"const GLenum {ev.Name} = {ev.Value};");
        }
        code.Header("");
        code.Header("");

        code.Header("// Commands");
        foreach (var cmd in sel.Commands)
        {
            var rv = cmd.Prototype.Visit(new ReturnValueRenderer(RemovePrefixes(cmd.Name, "gl"))).Code;
            var pms = cmd.Params.Select(c => c.ParamBody.Visit(new ParamRenderer()).Code);
            var pb = string.Join(", ", pms);
            code.Header($"{rv}({pb});");
        }

        code.Add("}");
        code.Add("");

        AnsiConsole.WriteLine("Writing code...");
        WritePage(folder, "gloc.cc", code.SourceLines);
        WritePage(folder, "gloc.hh", code.HeaderLines);
    }

    private static string RemovePrefixes(string s, params string[] prefixes)
    {
        var t = s;

        foreach (var pre in prefixes)
        {
            if (t.StartsWith(pre))
            {
                var next = t.Substring(pre.Length);
                if (string.IsNullOrEmpty(next)) continue;
                t = next;
            }
        }

        return t;
    }

    private static void VisitPrototype(Selection sel, IProtoVisitor typeFinder)
    {
        sel.Commands.SelectMany(c => c.Prototype).Visit(typeFinder);
    }

    private static void VisitParam(Selection sel, IParamVisitor typeFinder)
    {
        sel.Commands.SelectMany(c => c.Params).SelectMany(d => d.ParamBody).Visit(typeFinder);
    }

    private static void WriteTypes(SimpleWriter code, IEnumerable<TypeDef> types)
    {
        foreach (var t in types)
        {
            code.Header(t.CodeBlock.Visit(new TypeRenderer()).Code);
        }
    }

    private sealed class TypeFinder : IProtoVisitor, IParamVisitor
    {
        public HashSet<TypeDef> Types { get; } = new();

        public void VisitText(ProtoText member) { }
        public void VisitName(ProtoName member) { }
        public void VisitPType(ProtoPType ptype)
        {
            Add(ptype.Type);
        }

        public void VisitText(ParamText text) {}
        public void VisitName(ParamName name) {}
        public void VisitApiEntry(ParamApiEntry entry) { }
        public void VisitPtype(ParamPType member)
        {
            Add(member.Type);
        }

        private void Add(TypeDef? type)
        {
            while (true)
            {
                if (type == null) return;
                Types.Add(type);
                type = type.Requires;
            }
        }
    }

    private sealed class KindFinder : IProtoVisitor, IParamVisitor
    {
        internal Dictionary<KindDef, HashSet<TypeDef>> Kinds { get; } = new();

        public void VisitText(ProtoText member) {}
        public void VisitName(ProtoName member) {}
        public void VisitPType(ProtoPType ptype)
        {
            Add(ptype.Kind, ptype.Type);
        }

        private void Add(KindDef? kind, TypeDef? type)
        {
            if (kind == null) return;
            var hs = Get(kind);
            if (type != null)
            {
                hs.Add(type);
            }
        }

        public void VisitText(ParamText text) { }
        public void VisitName(ParamName name) { }
        public void VisitApiEntry(ParamApiEntry entry) { }
        public void VisitPtype(ParamPType member)
        {
            Add(member.Kind, member.Type);
        }

        private HashSet<TypeDef> Get(KindDef kind)
        {
            if (Kinds.TryGetValue(kind, out var r)) return r;
            r = [];
            Kinds[kind] = r;
            return r;
        }
    }

    private sealed class GroupFinder : IProtoVisitor, IParamVisitor
    {
        internal Dictionary<GroupDef, HashSet<TypeDef>> Groups { get; } = new();

        public void VisitText(ProtoText member) { }
        public void VisitName(ProtoName member) { }
        public void VisitPType(ProtoPType ptype)
        {
            Add(ptype.Group, ptype.Type);
        }

        private void Add(GroupDef? group, TypeDef? type)
        {
            if (group == null) return;
            var hs = Get(group);
            if (type != null)
            {
                hs.Add(type);
            }
        }

        public void VisitText(ParamText text) { }
        public void VisitName(ParamName name) { }
        public void VisitApiEntry(ParamApiEntry entry) { }
        public void VisitPtype(ParamPType member)
        {
            Add(member.Group, member.Type);
        }

        private HashSet<TypeDef> Get(GroupDef group)
        {
            if (Groups.TryGetValue(group, out var r)) return r;
            r = [];
            Groups[group] = r;
            return r;
        }
    }

    private sealed class ReturnValueRenderer(string newName) : IProtoVisitor
    {
        public void VisitText(ProtoText member)
        {
            Code += member.Value;
        }

        public void VisitName(ProtoName member)
        {
            Code += newName;
        }

        public void VisitPType(ProtoPType ptype)
        {
            if (ptype.Group != null)
            {
                Code += ptype.Group.Name;
            }
            else
            {
                Code += ptype.Type?.Name;
            }
        }

        public string Code { get; private set; } = "";
    }

    private sealed class ParamRenderer : IParamVisitor
    {
        public void VisitText(ParamText text)
        {
            Code += text.Value;
        }

        public void VisitName(ParamName name)
        {
            Code += name.Name;
        }

        public void VisitPtype(ParamPType ptype)
        {
            if (ptype.Group != null)
            {
                Code += ptype.Group.Name;
            }
            else
            {
                Code += ptype.Type?.Name;
            }
        }

        public void VisitApiEntry(ParamApiEntry entry)
        {
        }

        public string Code { get; private set; } = "";
    }

    private sealed class TypeRenderer : ITypeCodeVisitor
    {
        public string Code { get; private set; } = "";
        public void VisitText(TypeCodeText text)
        {
            Code += text.Value;
        }

        public void VisitApiEntry(TypeCodeApiEntry apiEntry)
        {
        }

        public void VisitName(TypeCodeName name)
        {
            Code += name.Name;
        }
    }

    private static bool Include(ProfileName? profile, InterfaceDef add)
    {
        return add.Profile == null || add.Profile == profile;
    }
}

internal static class Extensions
{
    public static string GetCommonPrefix(this IEnumerable<string> strings)
    {
        var list = strings.ToList();
        if (list.Count == 0) return "";
        if (list.Count == 1) return "";

        string prefix = list[0];
        foreach (var s in list.Skip(1))
        {
            int i = 0;
            int max = Math.Min(prefix.Length, s.Length);
            while (i < max && prefix[i] == s[i]) i++;
            prefix = prefix.Substring(0, i);
            if (prefix == "") break;
        }
        return prefix;
    }
}

internal class Selection
{
    internal HashSet<CommandDef> Commands { get; } = new();
    internal HashSet<EnumValue> EnumValues { get; } = new();

    public void Add(InterfaceDef add)
    {
        foreach (var x in add.Commands)
        {
            Commands.Add(x.Command);
        }

        foreach (var x in add.Enums)
        {
            foreach(var xx in x.Value)
            {
                EnumValues.Add(xx);
            }
        }
    }

    public void Remove(InterfaceDef add)
    {
        foreach (var x in add.Commands)
        {
            Commands.Remove(x.Command);
        }

        foreach (var x in add.Enums)
        {
            foreach (var xx in x.Value)
            {
                EnumValues.Remove(xx);
            }
        }
    }
}

class SimpleWriter
{
    internal List<string> SourceLines { get; } = new();
    internal List<string> HeaderLines { get; } = new();

    public void Header(string line)
    {
        HeaderLines.Add(line);
    }

    public void Source(string line)
    {
        SourceLines.Add(line);
    }

    public void Add(string line)
    {
        Header(line);
        Source(line);
    }
}