using System.Collections.Immutable;
using Glox.Registry;
using Spectre.Console;

namespace Glox.Cpp;

internal static class CppWriter
{
    private static void WritePage(DirectoryInfo folder, string page, IEnumerable<string> lines)
    {
        var path = Path.Combine(folder.FullName, page);
        File.WriteAllLines(path, lines);
    }

    internal static void Write(DirectoryInfo folder, Registry.Registry registry, NamedApi api, Version version, ProfileName? profile)
    {
        AnsiConsole.WriteLine("Generating code...");
        var features = registry.Features.Where(x => x.Api == api && x.Number <= version).OrderBy(x => x.Number);
        Selection sel = new();
        foreach (var feat in features)
        {
            foreach (var add in feat.Require)
            {
                if (Include(profile, add))
                {
                    sel.Add(add);
                }
            }

            foreach (var add in feat.Remove)
            {
                if (Include(profile, add))
                {
                    sel.Remove(add);
                }
            }
        }

        // todo(Gustav): collect types
        var typeFinder = new TypeFinder();
        sel.Commands.SelectMany(c => c.Params).SelectMany(d => d.ParamBody).Visit(typeFinder);
        sel.Commands.SelectMany(c => c.Prototype).Visit(typeFinder);
        var types = typeFinder.Types.ToImmutableArray();

        // todo(Gustav): fix command prefixes
        // todo(Gustav): group enums values into groups
        // todo(Gustav): replace naked types with classes
        // todo(Gustav: figure out how to use kinds... replacement function/factories
        // todo(Gustav): multiple enum values?

        AnsiConsole.WriteLine("Typing code...");
        SimpleWriter code = new();
        code.Header("#pragma once");
        code.Source("#include \"glox.hh\"");
        code.Add("");
        code.Add("// Code generated by the glox-sharp generator");
        code.Add("");
        WriteTypes(code, types.Where(t => t.GotAttributeFromName));
        code.Add("");
        code.Add("namespace gl");
        code.Add("{");

        code.Header("// Types");
        WriteTypes(code, types.Where(t => t.GotAttributeFromName == false));
        code.Header("");
        code.Header("");

        code.Header("// Enum values");
        foreach (var ev in sel.EnumValues)
        {
            code.Header($"const int {ev.Name} = {ev.Value};");
        }
        code.Header("");
        code.Header("");

        code.Header("// Commands");
        foreach (var cmd in sel.Commands)
        {
            var rv = cmd.Prototype.Visit(new ReturnValueRenderer()).Code;
            var pms = cmd.Params.Select(c => c.ParamBody.Visit(new ParamRenderer()).Code);
            var pb = string.Join(", ", pms);
            code.Header($"{rv}({pb});");
        }

        code.Add("}");
        code.Add("");

        AnsiConsole.WriteLine("Writing code...");
        WritePage(folder, "gloc.cc", code.SourceLines);
        WritePage(folder, "gloc.hh", code.HeaderLines);
    }

    private static void WriteTypes(SimpleWriter code, IEnumerable<TypeDef> types)
    {
        foreach (var t in types)
        {
            code.Header(t.CodeBlock.Visit(new TypeRenderer()).Code);
        }
    }

    private sealed class TypeFinder : IProtoVisitor, IParamVisitor
    {
        public HashSet<TypeDef> Types { get; } = new();

        public void VisitText(ProtoText member) { }
        public void VisitName(ProtoName member) { }
        public void VisitPType(ProtoPType member)
        {
            Add(member.Type);
        }

        public void VisitText(ParamText text) {}
        public void VisitName(ParamName name) {}
        public void VisitApiEntry(ParamApiEntry entry) { }
        public void VisitPtype(ParamPType member)
        {
            Add(member.Type);
        }

        private void Add(TypeDef? type)
        {
            while (true)
            {
                if (type == null) return;
                Types.Add(type);
                type = type.Requires;
            }
        }
    }

    private sealed class KindFinder : IProtoVisitor
    {
        private HashSet<KindDef> Kinds { get; } = new();

        public void VisitText(ProtoText member) {}
        public void VisitName(ProtoName member) {}
        public void VisitPType(ProtoPType member)
        {
            if (member.Kind == null) return;
            Kinds.Add(member.Kind);
        }
    }

    private sealed class ReturnValueRenderer : IProtoVisitor
    {
        public void VisitText(ProtoText member)
        {
            Code += member.Value;
        }

        public void VisitName(ProtoName member)
        {
            Code += member.Name;
        }

        public void VisitPType(ProtoPType member)
        {
            Code += member.Type?.Name;
        }

        public string Code { get; private set; } = "";
    }

    private sealed class ParamRenderer : IParamVisitor
    {
        public void VisitText(ParamText text)
        {
            Code += text.Value;
        }

        public void VisitName(ParamName name)
        {
            Code += name.Name;
        }

        public void VisitPtype(ParamPType ptype)
        {
            Code += ptype.Type?.Name;
        }

        public void VisitApiEntry(ParamApiEntry entry)
        {
        }

        public string Code { get; private set; } = "";
    }

    private sealed class TypeRenderer : ITypeCodeVisitor
    {
        public string Code { get; private set; } = "";
        public void VisitText(TypeCodeText text)
        {
            Code += text.Value;
        }

        public void VisitApiEntry(TypeCodeApiEntry apiEntry)
        {
        }

        public void VisitName(TypeCodeName name)
        {
            Code += name.Name;
        }
    }

    private static bool Include(ProfileName? profile, InterfaceDef add)
    {
        return add.Profile == null || add.Profile == profile;
    }
}

internal class Selection
{
    internal HashSet<CommandDef> Commands { get; } = new();
    internal HashSet<EnumValue> EnumValues { get; } = new();

    public void Add(InterfaceDef add)
    {
        foreach (var x in add.Commands)
        {
            Commands.Add(x.Command);
        }

        foreach (var x in add.Enums)
        {
            foreach(var xx in x.Value)
            {
                EnumValues.Add(xx);
            }
        }
    }

    public void Remove(InterfaceDef add)
    {
        foreach (var x in add.Commands)
        {
            Commands.Remove(x.Command);
        }

        foreach (var x in add.Enums)
        {
            foreach (var xx in x.Value)
            {
                EnumValues.Remove(xx);
            }
        }
    }
}

class SimpleWriter
{
    internal List<string> SourceLines { get; } = new();
    internal List<string> HeaderLines { get; } = new();

    public void Header(string line)
    {
        HeaderLines.Add(line);
    }

    public void Source(string line)
    {
        SourceLines.Add(line);
    }

    public void Add(string line)
    {
        Header(line);
        Source(line);
    }
}